# This workflow deploys the package on release.

name: Deploy

on:
  release:
    types: [published]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt
    - name: Test with pytest
      env:
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        TEST_DEVICE_AC: ${{ secrets.TEST_DEVICE_AC }}
        MOCK_CODE_AC: ${{ secrets.MOCK_CODE_AC }}
        MOCK_SUPPORT_CODE_AC: ${{ secrets.MOCK_SUPPORT_CODE_AC }}
        TEST_DEVICE_DH: ${{ secrets.TEST_DEVICE_DH }}
        MOCK_CODE_DH: ${{ secrets.MOCK_CODE_DH }}
        MOCK_SUPPORT_CODE_DH: ${{ secrets.MOCK_SUPPORT_CODE_DH }}
      run: |
        python -m pytest ./tests
  deploy:
    needs: pytest
    environment: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}